version: '3.8'

services:
  search-service:
    build: .
    container_name: search-service
    ports:
      - "3016:8006"  # 3016 externo → 8006 interno del microservicio Go
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
