version: '3.8'

services:
  catalog-service:
    build: .
    container_name: catalog-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - dynamodb-local
    networks:
      - shared-network
    restart: always

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb
    networks:
      - shared-network
    restart: always

volumes:
  dynamodb_data:

networks:
  shared-network:   
