version: '3.8'

services:
  pricing-service:
    build: .
    container_name: pricing-service
    ports:
      - "3018:8007"
    env_file:
      - .env
    restart: always
  postgres:
    image: postgres:13
    container_name: postgres-pricing
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
