source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
gem 'dotenv'
gem 'rackup'
gem 'puma'
gem 'faye-websocket'
gem 'eventmachine'

group :test do
  gem 'rspec'
  gem 'rack-test'
end
