version: '3.8'

services:
  image-service:
    build: .
    container_name: image-service
    ports:
      - "8007:8007"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
