version: '3.8'

services:
  update-product-service:
    build: .
    container_name: update-product-service
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - shared-network
    restart: always

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb
    networks:
      - shared-network
    restart: always

volumes:
  dynamodb_data:

networks:
  shared-network:   
