version: '3.8'

services:
  session-service:
    build: .
    container_name: session-service
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - redis-session
    restart: always

  redis-session:
    image: redis:alpine
    container_name: redis-session
    ports:
      - "6378:6379"
