version: '3.8'

services:
  category-service:
    build: .
    container_name: category-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - dynamodb-category
    restart: always

  dynamodb-category:
    image: amazon/dynamodb-local
    container_name: dynamodb-category
    ports:
      - "8001:8001"
    restart: always
