version: '3.8'

services:
  category-service:
    build: .
    container_name: category-service
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - dynamodb-category
    restart: always

  dynamodb-category:
    image: amazon/dynamodb-local
    container_name: dynamodb-category
    ports:
      - "8002:8000"  
    restart: always
