version: '3.8'

services:
  category-service:
    build: .
    container_name: category-service
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - dynamodb-category
    networks:
      - category-network
    restart: always

  dynamodb-category:
    image: amazon/dynamodb-local
    container_name: dynamodb-category
    ports:
      - "8002:8000"
    networks:
      - category-network
    restart: always
    volumes:
      - dynamo_data:/home/dynamodblocal  # ✅ Aquí se guarda la base

networks:
  category-network:

volumes:
  dynamo_data:  # ✅ Declaración del volumen persistente
