version: '3.8'

services:
  category-service:
    build: .
    container_name: category-service
    ports:
      - "${PORT}:${PORT}"        # Usa el puerto definido en .env (ej: 3001)
    env_file:
      - .env                     # Carga variables sensibles desde .env
    depends_on:
      - dynamodb-category
    networks:
      - category-network         # Red aislada
    restart: always

  dynamodb-category:
    image: amazon/dynamodb-local
    container_name: dynamodb-category
    ports:
      - "8002:8000"              # Externo 8002 para Postman; interno 8000 obligatorio
    networks:
      - category-network         # Misma red para comunicar con category-service
    restart: always

networks:
  category-network:
