version: "3.8"

services:
  user-profile-service:
    build: .
    container_name: user-profile-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres1@db:5432/db-users
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: db-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
