version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
