version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "8005:8005"
    env_file:
      - .env
    depends_on:
      - mariadb-inventory
    restart: always

  mariadb-inventory:
    image: mariadb:10.7
    container_name: mariadb-inventory
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - inventory_db_data:/var/lib/mysql
    restart: always

volumes:
  inventory_db_data:
