version: '3.8'

services:
  category-service:
    build: .
    container_name: category-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - dynamodb-category
    networks:
      - shared-network
    restart: always

  dynamodb-category:
    image: amazon/dynamodb-local
    container_name: dynamodb-category
    ports:
      - "8002:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    networks:
      - shared-network
    restart: always

volumes:
  dynamodb_data:

networks:
  shared-network:   # 🔁 Red interna que se crea sola
