version: '3.8'

services:
  search-service:
    build: .
    container_name: search-service
    ports:
      - "8006:8006"
    env_file:
      - .env
    depends_on:
      - cassandra
    restart: always

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "ShoeCluster"
      MAX_HEAP_SIZE: "256M"
      HEAP_NEWSIZE: "100M"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always

volumes:
  cassandra_data:
