name: Deploy createRoleService to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/user_domain/roleService/createRole/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/user_domain/roleService/createRole/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend/user_domain/roleService/createRole
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export FLASK_ENV=testing
          cd Backend/user_domain/roleService/createRole
          python -m unittest discover test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/role-service:create-role-latest ./Backend/user_domain/roleService/createRole

      - name: Push Docker image
        run: |
          docker push itsandy/role-service:create-role-latest

  deploy-qa:
    name: Deploy createRoleService - QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/roleService/createRole
            docker pull itsandy/role-service:create-role-latest
            docker stop create-role-service || true
            docker rm create-role-service || true
            docker run -d --name create-role-service -p 8007:8002 --env-file .env itsandy/role-service:create-role-latest

  deploy-prod:
    name: Deploy createRoleService - Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_PROD2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/roleService/createRole
            docker pull itsandy/role-service:create-role-latest
            docker stop create-role-service || true
            docker rm create-role-service || true
            docker run -d --name create-role-service -p 8007:8000 --env-file .env itsandy/role-service:create-role-latest
