name: Test ReadUser

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/user_domain/userProfileService/readUser/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/user_domain/userProfileService/readUser/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend/user_domain/userProfileService/readUser
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export FLASK_ENV=testing
          cd Backend/user_domain/userProfileService/readUser
          python -m unittest discover test
