name: Deploy createPriceService to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/product_domain/pricingService/createPrice/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/product_domain/pricingService/createPrice/**'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/pricing-service:create-price-latest ./Backend/product_domain/pricingService/createPrice

      - name: Push Docker image
        run: |
          docker push itsandy/pricing-service:create-price-latest

  deploy-qa:
    name: Deploy to QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PRODUCT_DOMAIN3_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRODUCT_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/product_domain/pricingService/createPrice
            docker pull itsandy/pricing-service:create-price-latest
            docker stop create-price-service || true
            docker rm create-price-service || true
            docker run -d --restart=always --name create-price-service -p 3018:4567 --env-file .env itsandy/pricing-service:create-price-latest

  deploy-prod:
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PRODUCT_DOMAIN3_PROD_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRODUCT_DOMAIN_PEM_PROD_KEY }}
          script: |
            cd ShoeCloud/Backend/product_domain/pricingService/createPrice
            docker pull itsandy/pricing-service:create-price-latest
            docker stop create-price-service || true
            docker rm create-price-service || true
            docker run -d --restart=always --name create-price-service -p 3018:4567 --env-file .env itsandy/pricing-service:create-price-latest
