name: Deploy deleteRoleService to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/user_domain/roleService/deleteRole/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/user_domain/roleService/deleteRole/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend/user_domain/roleService/deleteRole
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export FLASK_ENV=testing
          cd Backend/user_domain/roleService/deleteRole
          python -m unittest discover test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/role-service:delete-role-latest ./Backend/user_domain/roleService/deleteRole

      - name: Push Docker image
        run: |
          docker push itsandy/role-service:delete-role-latest

  deploy-qa:
    name: Deploy deleteRoleService - QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/roleService/deleteRole
            docker pull itsandy/role-service:delete-role-latest
            docker stop delete-role-service || true
            docker rm delete-role-service || true
            docker run -d --restart=always --name delete-role-service -p 8010:8002 --env-file .env itsandy/role-service:delete-role-latest

  deploy-prod:
    name: Deploy deleteRoleService - Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN2_PROD_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/roleService/deleteRole
            docker pull itsandy/role-service:delete-role-latest
            docker stop delete-role-service || true
            docker rm delete-role-service || true
            docker run -d --restart=always --name delete-role-service -p 8010:8002 --env-file .env itsandy/role-service:delete-role-latest
