name: Deploy authService - Login to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/user_domain/authService/login/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/user_domain/authService/login/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend/user_domain/authService/login
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          export FLASK_ENV=testing
          cd Backend/user_domain/authService/login
          python -m unittest discover test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/auth-service:login-latest ./Backend/user_domain/authService/login

      - name: Push Docker image
        run: |
          docker push itsandy/auth-service:login-latest

  deploy-qa:
    name: Deploy Login - QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/authService/login
            docker pull itsandy/auth-service:login-latest
            docker stop auth-login-service || true
            docker rm auth-login-service || true
            docker run -d --restart=always --name auth-login-service -p 8004:8001 --env-file .env itsandy/auth-service:login-latest

  deploy-prod:
    name: Deploy Login - Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_PROD_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PROD_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/authService/login
            docker pull itsandy/auth-service:login-latest
            docker stop auth-login-service || true
            docker rm auth-login-service || true
            docker run -d --restart=always --name auth-login-service -p 8004:8001 --env-file .env itsandy/auth-service:login-latest
