name: Deploy userProfileService to EC2

on:
  push:
    branches:
      - test2
      - main
    paths:
      - 'Backend/user_domain/userProfileService/createUser/**'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/user-profile-service:create-user-latest ./Backend/user_domain/userProfileService/createUser

      - name: Push Docker image
        run: |
          docker push itsandy/user-profile-service:create-user-latest

  deploy-qa:
    name: Deploy to QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/userProfileService/createUser
            docker pull itsandy/user-profile-service:create-user-latest
            docker stop create-user-service || true
            docker rm create-user-service || true
            docker run -d --name create-user-service -p 8000:8000 --env-file .env itsandy/user-profile-service:create-user-latest

  deploy-prod:
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_USER_DOMAIN_PROD_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_USER_DOMAIN_PROD_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/user_domain/userProfileService/createUser
            docker pull itsandy/user-profile-service:create-user-latest
            docker stop create-user-service || true
            docker rm create-user-service || true
            docker run -d --name create-user-service -p 8000:8000 --env-file .env itsandy/user-profile-service:create-user-latest
