name: Deploy searchProductService to EC2

on:
  push:
    branches:
      - test2
    paths:
      - 'Backend/product_domain/searchService/searchProduct/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/product_domain/searchService/searchProduct/**'

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run Unit Tests
        run: |
          cd Backend/product_domain/searchService/searchProduct
          go test ./...

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t itsandy/search-service:search-product-latest ./Backend/product_domain/searchService/searchProduct

      - name: Push Docker image
        run: |
          docker push itsandy/search-service:search-product-latest

  deploy-qa:
    name: Deploy to QA (test2)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/test2'

    steps:
      - name: Deploy to QA via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PRODUCT_DOMAIN3_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRODUCT_DOMAIN_PEM_KEY }}
          script: |
            cd ShoeCloud/Backend/product_domain/searchService/searchProduct
            docker pull itsandy/search-service:search-product-latest
            docker stop search-service || true
            docker rm search-service || true
            docker run -d --restart=always --name search-service -p 3016:8006 --env-file .env itsandy/search-service:search-product-latest

  deploy-prod:
    name: Deploy to Production (main)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PRODUCT_DOMAIN3_PROD_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PRODUCT_DOMAIN_PEM_PROD_KEY }}
          script: |
            cd ShoeCloud/Backend/product_domain/searchService/searchProduct
            docker pull itsandy/search-service:search-product-latest
            docker stop search-service || true
            docker rm search-service || true
            docker run -d --restart=always --name search-service -p 3016:8006 --env-file .env itsandy/search-service:search-product-latest
